language: node_js
node_js:
    - "7"

before_install:
    - sudo apt-get -qq update
#    - sudo apt-get install -y openjdk-8-jdk wget unzip
#    - wget https://services.gradle.org/distributions/gradle-3.4.1-bin.zip
#    - sudo mkdir /opt/gradle
#    - sudo unzip -d /opt/gradle gradle-3.4.1-bin.zip
#    - export PATH=$PATH:/opt/gradle/gradle-3.4.1/bin
    - mkdir -p ./src/objs/cpp
    - mkdir ./src/objs/headers
    - cp ./include/jsoncpp.cpp ./src/objs/cpp
    - rm -f $HOME/.gradle
    - pwd

script:
    - npm test
    - gradle tasks
    - gradle components
    - gradle dependencies
    - gradle clean
    - gradle --build-cache assemble
#    - ./build/exe/main/main/main
    