language: node_js
node_js:
    - "7"

before_install:
    - sudo apt-get -qq update
    # Install boost
    - sudo apt-get install libboost-all-dev
    # Install gradle 4.1
#    - sudo apt-get install -y openjdk-8-jdk wget unzip
    - wget https://services.gradle.org/distributions/gradle-4.1-bin.zip
    - sudo mkdir /opt/gradle
    - sudo unzip -d /opt/gradle gradle-4.1-bin.zip
    - export PATH=/opt/gradle/gradle-4.1/bin:$PATH
    # node app.js needs these dirs and file, FIXME
    - mkdir -p ./src/objs/cpp
    - mkdir ./src/objs/headers
    - cp ./include/jsoncpp.cpp ./src/objs/cpp
    
#    - rm -f $HOME/.gradle
#    - pwd

script:
    - npm test
    - gradle --version
    - gradle tasks
#    - gradle --rerun-tasks mainExecutable
#    - ./build/exe/main/main/main
    