language: node_js
node_js:
    - "7"

before_install:
    - sudo apt-get -qq update
#    - sudo apt-get install -y openjdk-8-jdk wget unzip
#    - wget https://services.gradle.org/distributions/gradle-3.4.1-bin.zip
#    - sudo mkdir /opt/gradle
#    - sudo unzip -d /opt/gradle gradle-3.4.1-bin.zip
#    - export PATH=$PATH:/opt/gradle/gradle-3.4.1/bin
    - mkdir -p ./src/objs/cpp
    - mkdir ./src/objs/headers
    - cp ./include/jsoncpp.cpp ./src/objs/cpp
    - pwd
script:
    - npm test
    - cat /home/travis/build/kevinmmurphy/quikbldr/src/objs/cpp/Choice.h
    - gradle build
    - ls -laR ./build
#    - ./build/exe/main/main/main
    